development:
  environment: "sandbox"
  username: "poster_1333750013_biz@sbcglobal.net"
  password: "1333750037"
  signature: "AKPjObvEZmvwXNYa7oDDiHbCgPJGAVD6-31IWQzoSbarHaP7d.L6mMCM	"
  application_id: "APP-80W284485P519543T"

test:
  environment: "sandbox"
  username: "poster_1333750013_biz@sbcglobal.net"
  password: "1333750037"
  signature: "AKPjObvEZmvwXNYa7oDDiHbCgPJGAVD6-31IWQzoSbarHaP7d.L6mMCM	"
  application_id: "APP-80W284485P519543T"

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"